### ISSUE TITLE
Wind velocity model

### ISSUE THREAD

**Issue by Tsroad** [ShrewdDoves/BN_OneContent#2]
model the wind velocity

**Comment by Tsroad** [comment]
Tsroad write：

Data preprocessing has been completed.

**Comment by kwen002** [comment]
Large Files MATLAB
https://www.mathworks.com/help/matlab/large-files-and-big-data.html
@Tsroad

**Comment by Tsroad** [comment]
This project is delay, and we will start new one, right? @kwen002
